### ISSUE TITLE
python 3 throws dict error for LDAP updates

### ISSUE THREAD

**Issue by seanmccanns** [seveas/python-hpilo#118]
Hi Seveas.

I opened a github account just to log this issue. so please be gentle as i don't log a lot of issues.

I'm running Python 3.4.4 (v3.4.4:737efcadf5a6, Dec 20 2015, 20:20:57) [MSC v.1600 64 bit (AM
D64)] on win32

ilo.mod_dir_config() is throwing this error
  for key, val in vars.iteritems():
AttributeError: 'dict' object has no attribute 'iteritems'

I looked up the error as I'm new to python. I might be doing something wrong .
Found this which tlaks about iteritems being depricated
http://stackoverflow.com/questions/20444340/iter-values-item-in-dictionary-does-not-work

However if  I change  *vars.iteritems():** to  _vars.iteritems(): in the below code 

 # create special case for element with text inside
        if dir_kerberos_keytab:
            keytab_el = etree.Element('DIR_KERBEROS_KEYTAB')
            keytab_el.text = dir_kerberos_keytab
            del vars['dir_kerberos_keytab']

        elements = []
            for key, val in vars.iteritems():
            if not val:
                continue
            if key.endswith('_priv'):
                if isinstance(val, basestring):
                    val = val.replace('oemhp_', '').replace('_priv', '').split(',')
                val = ','.join([str(privmap.get(x,x)) for x in val])
            else:
                val = str({True: 'Yes', False: 'No'}.get(val, val))
            elements.append(etree.Element(key.upper(), VALUE=val))

This code executes and makes the change to the privileges .
I don't know enough to change this with out  breaking python 2 compatibility to do a pull request. 

Thanks for reading this and creating the very useful module.

**Comment by seveas** [comment]
Hi Sean,

Thanks for making the effort to report this. This was broken ever since it was introduced in 308259d, as python3 does not support iteritems. I've now fixed this in 09500b5 and will do a release shortly.

If you find more bugs, please don't hesitate to report them.
