### PR TITLE
Fix error with python 3.9

### PR DESCRIPTION
**Pull request by champtar**
AttributeError: 'xml.etree.ElementTree.Element' object has no attribute 'getchildren'
getchildren() has been removed in python 3.9

Signed-off-by: Etienne Champetier <echampetier@anevia.com>

### CODE REVIEW

**Comment by seveas** [comment]
Heh, to my surprise this even works on python 2.7 :) Thanks!
